const MODELS=[
{id:"smollm2-360m-instruct-q4km",name:"SmolLM2 360M Instruct",filename:"SmolLM2-360M-Instruct-Q4_K_M.gguf",url:"https://huggingface.co/bartowski/SmolLM2-360M-Instruct-GGUF/resolve/main/SmolLM2-360M-Instruct-Q4_K_M.gguf?download=true",sha256:"2fa3f013dcdd7b99f9b237717fa0b12d75bbb89984cc1274be1471a465bac9c2",context:2048,threads:4,maxTokens:256},
{id:"smollm2-1.7b-instruct-q4km",name:"SmolLM2 1.7B Instruct",filename:"smollm2-1.7b-instruct-q4_k_m.gguf",url:"https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct-GGUF/resolve/main/smollm2-1.7b-instruct-q4_k_m.gguf?download=true",sha256:"decd2598bc2c8ed08c19adc3c8fdd461ee19ed5708679d1c54ef54a5a30d4f33",context:4096,threads:4,maxTokens:512}
];
const pending=new Map();let requestCounter=0,installed=[],loadedModel=null,history=[],activeStream=null,lastMetrics=null,remoteManifest=null,benchCancelled=false,lastBenchmark=null;
const $=s=>document.querySelector(s);

function nativeRequest(type,payload={}){
 return new Promise((resolve,reject)=>{const id=String(++requestCounter);pending.set(id,{resolve,reject});WorkbenchNative.postMessage(JSON.stringify({id,type,payload}));});
}
window.__nativeEvent=event=>{
 if(event.type==="reply"){const p=event.payload,w=pending.get(p.id);if(!w)return;pending.delete(p.id);p.ok?w.resolve(p.data):w.reject(new Error(p.error||"Kernel error"));return;}
 if(event.type==="token"){if(activeStream)activeStream(event.payload.chunk||"");return;}
 if(event.type==="download_progress"){const pct=Number(event.payload.percent||0);$("#download-progress").value=pct;$("#model-status").textContent="Downloading… "+pct.toFixed(1)+"%";}
};
function toast(m){const e=$("#toast");e.textContent=m;e.style.display="block";clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.style.display="none",3500);}
function switchTab(n){document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.id===n));document.querySelectorAll("#tabs button").forEach(x=>x.classList.toggle("active",x.dataset.tab===n));}
function selectedModel(){return MODELS[$("#model-select").selectedIndex||0];}
function generationSettings(){return{max_tokens:Number($("#max-tokens").value),temperature:Number($("#temperature").value),top_p:.95,top_k:40,repeat_penalty:1.1};}
function buildPrompt(messages,systemText){let o="<|im_start|>system\n"+systemText.trim()+"<|im_end|>\n";for(const m of messages)o+="<|im_start|>"+m.role+"\n"+m.content+"<|im_end|>\n";return o+"<|im_start|>assistant\n";}
function metricText(m){if(!m)return"No metrics.";const evaluated=m.evaluated_prompt_tokens??m.prompt_tokens,rate=m.prompt_seconds>0?evaluated/m.prompt_seconds:0;return"Prompt "+m.prompt_tokens+" tok · cached "+(m.cached_prompt_tokens||0)+" · evaluated "+evaluated+" · prefill "+rate.toFixed(1)+" tok/s · TTFT "+Number(m.ttft_seconds).toFixed(2)+"s · decode "+Number(m.tokens_per_second).toFixed(2)+" tok/s · total "+Number(m.total_seconds).toFixed(2)+"s";}
function renderMetrics(m){if(!m)return;lastMetrics=m;$("#metrics").textContent=metricText(m);}
function appendMessage(role,content){const box=document.createElement("div");box.className="message";const label=document.createElement("div");label.className="role";label.textContent=role==="user"?"You":"Assistant";const body=document.createElement("div");body.textContent=content;box.append(label,body);$("#chat-view").append(box);$("#chat-view").scrollTop=$("#chat-view").scrollHeight;return body;}
async function refreshModels(){installed=await nativeRequest("models.list");const m=selectedModel(),has=installed.some(x=>x.filename===m.filename);$("#download-button").disabled=has;$("#load-button").disabled=!has||loadedModel===m.filename;$("#delete-button").disabled=!has;$("#unload-button").disabled=!loadedModel;}
async function refreshKernel(){const i=await nativeRequest("kernel.info");$("#kernel-line").textContent="kernel "+i.kernel_version+" · workbench "+i.workbench_version;$("#runtime-info").textContent=i.runtime;await refreshModels();}
async function loadModelSelection(){const m=selectedModel();$("#context").value=m.context;$("#threads").value=m.threads;$("#max-tokens").value=m.maxTokens;await refreshModels();}
async function generate(prompt,onChunk){activeStream=onChunk;try{const r=await nativeRequest("generation.start",Object.assign({prompt},generationSettings()));renderMetrics(r);return r;}finally{activeStream=null;}}
async function sendChat(){if(!loadedModel)return toast("Load a model first.");const text=$("#chat-input").value.trim();if(!text)return;history.push({role:"user",content:text});appendMessage("user",text);$("#chat-input").value="";const body=appendMessage("assistant","");let response="";try{await generate(buildPrompt(history,$("#system-prompt").value),chunk=>{response+=chunk;body.textContent+=chunk;$("#chat-view").scrollTop=$("#chat-view").scrollHeight;});history.push({role:"assistant",content:response});}catch(e){body.textContent+="\n[error: "+e.message+"]";}}
async function checkUpdate(show=true){try{const d=await nativeRequest("update.check");remoteManifest=d.manifest;const t=d.update_available?"Update available: "+d.local_version+" → "+d.remote_version:"Current workbench is up to date (v"+d.local_version+").";$("#update-status").textContent=t;$("#update-button").textContent=d.update_available?"Update available":"Up to date";if(show)toast(t);return d;}catch(e){$("#update-status").textContent="Update check failed: "+e.message;if(show)toast(e.message);return null;}}
async function applyUpdate(){if(!remoteManifest){const c=await checkUpdate(false);if(!c||!c.update_available)return;}try{$("#update-status").textContent="Downloading and verifying workbench…";await nativeRequest("update.apply",{manifest:remoteManifest});$("#update-status").textContent="Update installed. Reloading…";await nativeRequest("update.reload");}catch(e){$("#update-status").textContent="Update failed: "+e.message;}}
async function runBenchmark(){if(!loadedModel)return toast("Load a model first.");benchCancelled=false;lastBenchmark=null;$("#bench-metrics").textContent="Waiting for first completed turn…";let suite;try{suite=await fetch("benchmarks/chatbot-v0.json").then(r=>{if(!r.ok)throw new Error("HTTP "+r.status);return r.json();});}catch(e){$("#bench-status").textContent="Could not load benchmark: "+e.message;return;}const threads=new Map(),turns=[];$("#bench-progress").max=suite.turns.length;$("#bench-progress").value=0;
 for(let i=0;i<suite.turns.length&&!benchCancelled;i++){const turn=suite.turns[i],thread=threads.get(turn.thread)||[];thread.push({role:"user",content:turn.prompt});threads.set(turn.thread,thread);$("#bench-status").textContent="Turn "+(i+1)+"/"+suite.turns.length+" · "+turn.category;$("#bench-preview").textContent="Prompt\n"+turn.prompt+"\n\nResponse\n";let response="";try{const metrics=await generate(buildPrompt(thread,suite.system_prompt||"You are a capable local assistant."),chunk=>{response+=chunk;$("#bench-preview").textContent+=chunk;});thread.push({role:"assistant",content:response});turns.push(Object.assign({},turn,{response,metrics}));$("#bench-progress").value=i+1;$("#bench-metrics").textContent="Turn "+(i+1)+": "+metricText(metrics);}catch(e){turns.push(Object.assign({},turn,{response,error:e.message}));break;}}
 lastBenchmark={schema:1,type:"benchmark_result",suite:suite.id,generated_at:new Date().toISOString(),complete:!benchCancelled&&turns.length===suite.turns.length,model:loadedModel,turns};$("#bench-status").textContent=lastBenchmark.complete?"Benchmark complete.":"Stopped after "+turns.length+" turn(s).";
}
async function boot(){MODELS.forEach(m=>$("#model-select").add(new Option(m.name,m.id)));await loadModelSelection();await refreshKernel();document.querySelectorAll("#tabs button").forEach(b=>b.addEventListener("click",()=>switchTab(b.dataset.tab)));$("#model-select").addEventListener("change",loadModelSelection);
 $("#download-button").addEventListener("click",async()=>{const m=selectedModel();$("#model-status").textContent="Starting download…";try{const r=await nativeRequest("model.download",m);$("#model-status").textContent="Verified: "+r.filename;await refreshModels();}catch(e){$("#model-status").textContent="Download failed: "+e.message;}});
 $("#load-button").addEventListener("click",async()=>{const m=selectedModel();$("#model-status").textContent="Loading…";try{const r=await nativeRequest("model.load",{filename:m.filename,context:Number($("#context").value),threads:Number($("#threads").value)});loadedModel=m.filename;$("#model-status").textContent="Loaded "+m.name+" · "+r.parameters+" parameters";$("#runtime-info").textContent=r.system_info||$("#runtime-info").textContent;await refreshModels();}catch(e){$("#model-status").textContent="Load failed: "+e.message;}});
 $("#unload-button").addEventListener("click",async()=>{await nativeRequest("model.unload");loadedModel=null;$("#model-status").textContent="No model loaded.";await refreshModels();});
 $("#delete-button").addEventListener("click",async()=>{const m=selectedModel();await nativeRequest("model.delete",{filename:m.filename});if(loadedModel===m.filename)loadedModel=null;await refreshModels();});
 $("#send-button").addEventListener("click",sendChat);$("#stop-button").addEventListener("click",()=>nativeRequest("generation.stop"));$("#bench-run").addEventListener("click",runBenchmark);$("#bench-stop").addEventListener("click",async()=>{benchCancelled=true;await nativeRequest("generation.stop");});
 $("#check-update").addEventListener("click",()=>checkUpdate());$("#update-button").addEventListener("click",async()=>{const r=await checkUpdate(false);if(r&&r.update_available)await applyUpdate();});$("#apply-update").addEventListener("click",applyUpdate);
 $("#save-token").addEventListener("click",async()=>{const token=$("#github-token").value.trim();await nativeRequest("secret.set",{name:"github_token",value:token});$("#github-token").value="";toast("GitHub token stored with Android Keystore.");});
 $("#clear-token").addEventListener("click",async()=>{await nativeRequest("secret.delete",{name:"github_token"});$("#github-token").value="";toast("GitHub token cleared.");});
 $("#push-benchmark").addEventListener("click",async()=>{if(!lastBenchmark)return toast("Run a benchmark first.");try{await nativeRequest("github.pushResult",{filename:"benchmark-"+Date.now()+".json",content:JSON.stringify(lastBenchmark,null,2)});toast("Benchmark result pushed.");}catch(e){toast("Push failed: "+e.message);}});
 checkUpdate(false);
}
boot().catch(e=>{document.body.innerHTML="<pre style='padding:20px;color:white'>Workbench boot failed\n"+(e.stack||e)+"</pre>";});
